// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAPbOmWhacXnjmXB0j-nDHn5_pNmUyJRSs',
    appId: '1:493801210955:web:f760821a0f3f7d4a3a39ce',
    messagingSenderId: '493801210955',
    projectId: 'pest-detection-59c57',
    authDomain: 'pest-detection-59c57.firebaseapp.com',
    storageBucket: 'pest-detection-59c57.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAC7FHOLg0WZ_O3gqgZU8WAIB45N-OAXs0',
    appId: '1:493801210955:android:9afe97b7e06e371a3a39ce',
    messagingSenderId: '493801210955',
    projectId: 'pest-detection-59c57',
    storageBucket: 'pest-detection-59c57.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBDO-ZN9TZZeZ21NwS-ah2DAgzNyk2xDgM',
    appId: '1:493801210955:ios:ec321708690f40a83a39ce',
    messagingSenderId: '493801210955',
    projectId: 'pest-detection-59c57',
    storageBucket: 'pest-detection-59c57.appspot.com',
    iosClientId: '493801210955-djc88r8496brtmvltrkuif045qfuco0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pestDetection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBDO-ZN9TZZeZ21NwS-ah2DAgzNyk2xDgM',
    appId: '1:493801210955:ios:ec321708690f40a83a39ce',
    messagingSenderId: '493801210955',
    projectId: 'pest-detection-59c57',
    storageBucket: 'pest-detection-59c57.appspot.com',
    iosClientId: '493801210955-djc88r8496brtmvltrkuif045qfuco0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.pestDetection',
  );
}
